project:
  type: website

website:
  title: "Vineeth Krishna Talasila"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications & Talks

format:
  html:
    theme: flatly
    css: styles.css
    toc: true